import "./globals.css";

export const metadata = {
  title: "Web 2 Demo 1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
